### ISSUE TITLE
Agora 3.0.1 native sdk 

### ISSUE THREAD

**Issue by softsan** [AgoraIO-Community/Agora-RTC-SDK-for-Xamarin#11] opened 2020-05-29 18:06 UTC
Hi,

I see Agora released native 3.0.1 SDK for iOS and Android on 27th May 2020.

https://docs.agora.io/en/Video/release_ios_video?platform=iOS#v301
https://docs.agora.io/en/Video/release_android_video?platform=Android#v301

So is there any chance to update the same for Xamarin nuget package.
Thanks.

**Comment by mleviathan** [comment] 2020-06-01 15:48
Hello, I worked on this and got a working solution, but only for Android. This repo doesn't include any guidelines on how to contribute, so I'm unable to push my changes ATM.   
@sbokatuk how can I create a Pull Request on this repo?

**Comment by alexsorokoletov** [comment] 2020-06-01 22:46
@mleviathan Sergey or me we can't really help with the access rights to the repo.
I think if you make a fork of the repo then you might be able to create a pull request.

**Comment by mleviathan** [comment] 2020-06-02 08:56
> @mleviathan Sergey or me we can't really help with the access rights to the repo.
> I think if you make a fork of the repo then you might be able to create a pull request.

Yes I forked the repo and pushed changes on my fork, I was wondering if you have any guidelines to read before creating the PR, for example I only worked on the android version, maybe you want to accept only upgrades for all platforms. I also added the obsolete decorator which some developers don't want to see in their code as it removes a warning from the IDE and stuff like that

**Comment by brettchangus** [comment] 2020-06-02 18:37
When I try to use the latest Android nuget, labeled 3.0.1, that was uploaded today, I get an error when RtcEngine.Create is called:

06-02 11:29:09.888 E/linker  ( 9333): "/data/app/com.dreamteammobile.formsagora.DT_Samples_Agora_Cross-89fn-as8E-4fA3yg4tnAbA==/lib/x86/libagora-rtc-sdk.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)
**Java.Lang.UnsatisfiedLinkError:** 'dlopen failed: "/data/app/com.dreamteammobile.formsagora.DT_Samples_Agora_Cross-89fn-as8E-4fA3yg4tnAbA==/lib/x86/libagora-rtc-sdk.so" has text relocations (https://android.googlesource.com/platform/bionic/+/master/android-changes-for-ndk-developers.md#Text-Relocations-Enforced-for-API-level-23)'

The same thing happens when I try to build this project myself with the latest 3.0.1 SDK. Any advice on how to fix this would be much appreciated.

If I use the older nuget (3.0.0.2), it seems to work fine.

**Comment by mleviathan** [comment] 2020-06-02 18:45
@brettchangus are you using an emulator? If so, try with a physical device, it'll work. The problem here is the x86 lib which has been poorly compiled by Agora, you should open a ticket on their site.

**Comment by sbokatuk** [comment] 2020-06-02 18:46
@brettchangus could you please share which android SDK, and which version of tools(xamarin) you using, also which device and OS version you running. I will try to reproduce, currently we as usually tested on sample app, made test call and released 3.0.1

**Comment by brettchangus** [comment] 2020-06-02 19:15
@mleviathan -- thanks, I'll try on a device but as I'm working remotely, it will take me a bit.

@sbokatuk -- I'm using the latest VS 2019 (16.5.5) and I'm testing with the DreamTeam FormsWithNativeNugets sample app (DT.Samples.Agora.Cross), which I've updated to reference the latest XF packages (4.6.0.800) and targeting Android 10.0. With the older nuget, that app seems to work fine.

I've tried building this project (wrapper library) with the latest Android SDK from Agora (3.0.1) and updated the project references to use the latest files as some of were renamed. I've tried targeting Android 4.4 and Android 10 and neither seems to work. The dll builds fine, but the sample app crashes with the error mentioned above when the sdk is loaded.

As @mleviathan suggests, maybe there is a problem with the latest x86 libagora-rtc-sdk.so library.

**Comment by brettchangus** [comment] 2020-06-02 21:21
Verified that reverting to the 3.0.0.2 SDK allows me to build this project correctly so it seems likely Agora broke something in 3.0.1 for x86. I've filed a ticket with their support team.

Appreciate the quick feedback!

**Comment by sbokatuk** [comment] 2020-06-02 22:04
@brettchangus I'll also look on changes related x86 arch between 3.0.0.2 and 3.0.1 to exclude anything inside nugget and lib binding

**Comment by brettchangus** [comment] 2020-06-03 03:25
@sbokatuk Sounds good, thanks. 

Agora just replied back saying that emulators aren't supported but that they tested with their sample code on the Android emulator and it worked so I'm not sure what is going on.

I also tried building iOS w/ 3.0.1 off the current code base but when I generated the ApiDefinition, it looks like quite a bit has changed compared to what is currently checked in.

**Comment by brettchangus** [comment] 2020-06-08 18:37
Agora confirmed the x86 compilation error is a bug in their 3.0.1 SDK. They recommend using 3.0.0.2 when using an emulator for now.

**Closed** 2020-06-18 02:17 UTC
